"""reset, fixed columns

Revision ID: 06011cd8f8f9
Revises: 
Create Date: 2023-04-21 23:24:39.258162

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '06011cd8f8f9'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=20), nullable=False),
    sa.Column('program', sa.String(length=20), nullable=True),
    sa.Column('year_validity', sa.String(length=20), nullable=True),
    sa.Column('sr_code', sa.String(length=8), nullable=True),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('id_img_data', sa.LargeBinary(), nullable=False),
    sa.Column('id_img_name', sa.Text(), nullable=False),
    sa.Column('id_img_mimetype', sa.Text(), nullable=False),
    sa.Column('sign_img_data', sa.LargeBinary(), nullable=False),
    sa.Column('sign_img_name', sa.Text(), nullable=False),
    sa.Column('sign_img_mimetype', sa.Text(), nullable=False),
    sa.Column('contact_person', sa.String(length=20), nullable=True),
    sa.Column('address', sa.String(length=20), nullable=True),
    sa.Column('contact_number', sa.String(length=20), nullable=True),
    sa.Column('final_id_img', sa.LargeBinary(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('email'),
    sa.UniqueConstraint('full_name'),
    sa.UniqueConstraint('sr_code')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user')
    # ### end Alembic commands ###
