"""empty message

Revision ID: 328292fc6c3c
Revises: 
Create Date: 2023-04-21 05:56:32.697151

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '328292fc6c3c'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('full_name', sa.String(length=150), nullable=True),
    sa.Column('program', sa.String(length=64), nullable=True),
    sa.Column('sr_code', sa.String(length=5), nullable=True),
    sa.Column('year_validity', sa.String(length=100), nullable=True),
    sa.Column('address', sa.String(length=164), nullable=True),
    sa.Column('contact_person', sa.String(length=164), nullable=True),
    sa.Column('contact_num', sa.String(length=164), nullable=True),
    sa.Column('email', sa.String(length=164), nullable=True),
    sa.Column('id_img_data', sa.LargeBinary(), nullable=True),
    sa.Column('id_img_name', sa.Text(), nullable=True),
    sa.Column('id_img_mimetype', sa.Text(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_address'), ['address'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_contact_num'), ['contact_num'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_contact_person'), ['contact_person'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_full_name'), ['full_name'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_program'), ['program'], unique=False)
        batch_op.create_index(batch_op.f('ix_user_sr_code'), ['sr_code'], unique=True)
        batch_op.create_index(batch_op.f('ix_user_year_validity'), ['year_validity'], unique=False)

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_year_validity'))
        batch_op.drop_index(batch_op.f('ix_user_sr_code'))
        batch_op.drop_index(batch_op.f('ix_user_program'))
        batch_op.drop_index(batch_op.f('ix_user_full_name'))
        batch_op.drop_index(batch_op.f('ix_user_email'))
        batch_op.drop_index(batch_op.f('ix_user_contact_person'))
        batch_op.drop_index(batch_op.f('ix_user_contact_num'))
        batch_op.drop_index(batch_op.f('ix_user_address'))

    op.drop_table('user')
    # ### end Alembic commands ###
