"""empty message

Revision ID: ff060c9fb53e
Revises: 06011cd8f8f9
Create Date: 2023-04-22 06:03:33.904351

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ff060c9fb53e'
down_revision = '06011cd8f8f9'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_column('final_id_img')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.add_column(sa.Column('final_id_img', sa.BLOB(), nullable=False))

    # ### end Alembic commands ###
